### ISSUE TITLE
.gitignore is not created

### ISSUE THREAD

**Issue by arnaugomez** [mrmilu/generator-react-mrmilu#10]
Not only does the project generator not create a `.gitignore` file, bit also stages the changes. 

So when I create a .gitignore file for git to ignore the `node_modules` folder, the contents inside the folder are not getting ignored.

This is a picture of what I see in my terminal when I run `git status`:

![imagen](https://user-images.githubusercontent.com/66358043/112988766-7b84f400-9164-11eb-98fe-2593c2d8b041.png)

**Comment by hazzo** [comment]
This is not happening any more in version 1.7.0. Fill free to reopen if still an issue.
